### ISSUE TITLE
А может эта штука скачивать тестовые релизы?

### ISSUE THREAD

**Issue by mors1eska** [arkuznetsov/yard#2]
На юзерс помимо основных выкладывают тестовые релизы, есть ли возможность скачать их?
![image](https://user-images.githubusercontent.com/34914654/91553783-a12fed80-e936-11ea-894a-5b5c930eb837.png)

**Comment by arkuznetsov** [comment]
Сейчас нет, надо немного подпилить.

**Comment by arkuznetsov** [comment]
@mors1eska Добавил возможность получения инфы по тестовым релизам в develop. Сейчас реализована возможность только вывода их в список. команду закачки еще нужно доделать.
