### ISSUE TITLE
Выгрузка в Git не может быть выполнена когда установлено несколько модулей EDT для ring

### ISSUE THREAD

**Issue by ilya2184** [arkuznetsov/yard#21]
https://github.com/arkuznetsov/yard/blob/ee87abbd2ca151837ef185031d24289da483a8f7/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8%D0%92%D0%93%D0%B8%D1%82.os#L653

Текст ошибки:
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\yard\src\Классы\ВыгрузкаКонфигурацииВГит.os / Ошибка в строке: 665 / [ERROR ] Неправильный вызов команды (для справки см. "ring help"): Specify version for module "edt". Available versions: 2021.2.12, 2021.3.0.
}

ввод: ring help modules
вывод: Доступные модули:

  edt@2021.3.0:x86_64 - 1C:Enterprise Development Tools Ring Cli
  edt@2021.2.12:x86_64 - 1C:Enterprise Development Tools Ring Cli
  license@0.15.0:x86_64 - Утилита для работы с лицензиями.

**Comment by arkuznetsov** [comment]
Попробуй последнюю версию из develop.
