### ISSUE TITLE
Выгрузка в гит копирует не все нужные для EDT файлы

### ISSUE THREAD

**Issue by Iscarimet** [arkuznetsov/yard#22]
https://github.com/arkuznetsov/yard/blob/fe30d0ee43db7b56aa9c9f94e2d73656130d0a2f/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8%D0%92%D0%93%D0%B8%D1%82.os#L692

Маска поиска файлов исключает файл ".project", по которому EDT находит в папке проект конфигурации.
Нужно добавить его в маску.

Или можно несколькими строками ранее заменить "--project-name tmp" на "**--project <КаталогВФорматеЕДТ>**".
Таким образом можно создавать проект прямо в папке гита, обойдясь без копирования.

**Comment by Iscarimet** [comment]
Закрываю потому что создал pull-request и его слили в develop
#24

**Comment by Daabramov** [comment]
@Iscarimet 

Привет, так было сделано специально по следующим причинам:

1) В каталоге помимо файла .project могут быть и другие файлы (папка .settings которые содержит настройки плагинов для ЕДТ) или например bsl-language-server.json. 
2) Если имя проекта в существующем репо отличается от имени конфигурации 1С

Однако и в старой реализации я понимаю, что отсутствие файла .project не дает возможности запустить ЕДТ просто так.

Предложения:
1) Проверять наличие файла .project в репозитории, если он есть, то брать его, если нет, то использовать стандартный
2) Чтобы не перемещать исходники из одной папки в другую можно копировать "остальные" файлы и помещать их уже в конце обратно.

**Comment by Iscarimet** [comment]
@Daabramov

Согласен с предложениями. Сделаю следующее:
1. Папку .settings предварительно скопирую из текущей репы во временный каталог, после выгрузки проекта в репу, удаляю оттуда стандартную папку и возвращаю сохраненную обратно.
2. То же самое делаю с файлом .project
3. Возможно стоит таким же образом сохранять состояние папки DT-INF, потому что там лежит файл с версией рантайма
4. Остальное остаётся как есть в PR

**Comment by Daabramov** [comment]
> @Daabramov
> 
> Согласен с предложениями. Сделаю следующее:
> 
> 1. Папку .settings предварительно скопирую из текущей репы во временный каталог, после выгрузки проекта в репу, удаляю оттуда стандартную папку и возвращаю сохраненную обратно.
> 2. То же самое делаю с файлом .project
> 3. Возможно стоит таким же образом сохранять состояние папки DT-INF, потому что там лежит файл с версией рантайма
> 4. Остальное остаётся как есть в PR

3. В этом особо смысла нет, так как версия проекта по сути уже определяется указанием версии рантайм (параметр -v "8.3.*.*"), если вдруг там окажется какая-то другая версия, отличная от версии платформы при выгрузке конфы, то она просто будет не валидная и это не взлетит.

С остальным все ок.
