### ISSUE TITLE
Добавить флаг "СнятьСПоддержки"

### ISSUE THREAD

**Issue by Iscarimet** [arkuznetsov/yard#25]
При использовании YARD для автоматического обновления ветки с типовой конфигурацией возникает потребность снимать эту конфигурацию с поддержки, потому что на проекте конфигурация была изначально снята с поддержки.

Это можно сделать на разных стадиях работы инструмента. Я сейчас вижу безболезненный вариант при конвертации в формат EDT. Достаточно после конвертации удалить файл "ParentConfigurations.bin" в папке "Configuration" исходников.

**Comment by arkuznetsov** [comment]
@Iscarimet Я всегда был против снятия с поддержки конфигураций. Если нужна функциональность, присылайте PR.
