### ISSUE TITLE
Не получается выполнить команду list

### ISSUE THREAD

**Issue by mors1eska** [arkuznetsov/yard#3]
Установил yard через opm
Хелп работает, пытаюсь поиграться с чтением релизов - не получается
![image](https://user-images.githubusercontent.com/34914654/93711299-d73b4880-fb55-11ea-9766-9d15d5739729.png)

**Comment by arkuznetsov** [comment]
Там проблема с заголовками, возьмите из ветки develop.

**Comment by mors1eska** [comment]
![image](https://user-images.githubusercontent.com/34914654/94371810-e5fb9f80-0101-11eb-9d3a-f8bc7078d6d5.png)

Поставил из девелоп, все равно выдает ошибку =(
Что может быть?

**Comment by arkuznetsov** [comment]
А вы пробовали указать пользователя и пароль от ИТС?
Еще иногда может потребоваться, прежде чем получать данные с сайта скриптом, зайти 1 раз на сайт через браузер.

**Comment by mors1eska** [comment]
Спасибо, что-то с логином паролем я затупил =(

Дело явно сдвинулось, но попробовал опять строку из примера и до конца со своей авторизацией

В отладке вот такую ошибку показывает
![image](https://user-images.githubusercontent.com/34914654/94459132-95e31280-01bf-11eb-9889-d66e06502b8f.png)

что может быть не так?

**Comment by arkuznetsov** [comment]
Еще раз обновитесь из ветки develop и попробуйте снова.

**Comment by mors1eska** [comment]
что-то стало хуже

![image](https://user-images.githubusercontent.com/34914654/94558207-545a7200-0268-11eb-95a5-d5ebb1c988bd.png)

в отладке ничего дополнительного не выводит

**Comment by arkuznetsov** [comment]
Сорри, рука дрогнула. Проверяй.

**Comment by mors1eska** [comment]
Огонь, прошло =) Буду дальше копать
