### ISSUE TITLE
Ошибочный путь распаковки дистрибутивов

### ISSUE THREAD

**Issue by pravets** [arkuznetsov/yard#30]
Добрый день. Обнаружил ошибку при распаковке дистрибутивов.

Пример команды yard.os ea --path=E:\xml\tmp1\distr\Money --extract-path E:\xml\tmp1\tmplts

В результате распаковка проходит по следующему пути:
ИНФОРМАЦИЯ - Записан файл E:\xml\tmp1\tmplts\**2.0.41.34**\Money\2.0.41.34\1cv8.cfu

В каталоге для распаковки ошибочно создается подкаталог с номером релиза, затем в нем уже создается каталог с именем конфигурации и снова создается подкаталог с номером релиза.
И соответственно, если затем попытаться запустить сборку cf, она упадёт, так как по ожидаемому пути не обнаружит файлов cfu.

Ошибка воспроизводится как при использовании файла конфигурации, так и просто при запуске команды --extract-all

Могу оформить pull request с фиксом, там буквально 2 строки в классе распаковщика поправить надо.

**Comment by arkuznetsov** [comment]
@pravets Попробуйте указать параметр --extract-dir Money.
