### ISSUE TITLE
Защита от DDOS-атак при загрузке релизов

### ISSUE THREAD

**Issue by vkislitsin** [arkuznetsov/yard#37]
Получаю ошибку при попытке загрузки релизов:

> ОТЛАДКА - [oscript.app.yard] - Авторизация: Получена строка регистрации от ресурса "https://login.1c.ru": "inviteCode=&username=xxxx&password=yyyy&execution=&_eventId=submit&geolocation=&submit=Войти&rememberMe=on"
> КРИТИЧНАЯОШИБКА - [oscript.app.yard] - {Модуль C:\Program Files (x86)\OneScript\lib\asserts\src\xunit-asserts.os / Ошибка в строке: 30 / Сравниваемые значения (403; 302) не равны, а хотели, чтобы были равны.
> Код переадресации не соответствует ожидаемому!}
> 

Проверил получаемый ответ от сервера - он содержит страницу с текстом "Проверка браузера перед переходом на сайт" и следующий скрипт:

> <script type="text/javascript">var lang=navigator.language,host=window.location.hostname;"ru"==lang||"ru-RU"==lang?(document.getElementById("title").innerHTML="Проверка браузера перед переходом на сайт "+host,document.getElementById("description").innerHTML="Это автоматический процесс. Вы будете перенаправлены на запрашиваемый ресурс в ближайшее время.<br>Пожалуйста ожидайте...",document.getElementById("link").innerHTML="Защита от DDoS-атак DDos-Guard"):(document.getElementById("title").innerHTML="Checking your browser accessing "+host,document.getElementById("description").innerHTML="This process is automatic. Your browser will redirect to your requested content shortly.<br>Please allow up to 5 seconds...",document.getElementById("link").innerHTML="DDoS protection by DDos-Guard");</script>

**Comment by arkuznetsov** [comment]
Пока решения этой проблемы со стороны yard, к сожалению, не придумано.

**Comment by vkislitsin** [comment]
Может быть хотя бы диагностическое сообщение с полным содержимым ответа сервера можно приводить, в случае получения неправильных ответов? Сообщение о невалидном коде переадресации не очень информативно. Приходится вносить изменения в скрипт, чтобы получить содержимое ответа и понять причину.

> Ошибка в строке: 30 / Сравниваемые значения (403; 302) не равны, а хотели, чтобы были равны.
> Код переадресации не соответствует ожидаемому!}

**Comment by arkuznetsov** [comment]
Да, сейчас там стандартное сообщение от библиотеки asserts. Если уже есть код, детализирующий описание ошибки, то буду благодарен за pull request.
