### ISSUE TITLE
Код переадресации не соответствует ожидаемому

### ISSUE THREAD

**Issue by mors1eska** [arkuznetsov/yard#4]
![image](https://user-images.githubusercontent.com/34914654/97811273-7772aa00-1c8a-11eb-846d-38d9f3370d7f.png)
![image](https://user-images.githubusercontent.com/34914654/97811515-219f0180-1c8c-11eb-8b8f-366260e3d404.png)

При этом команда list работает (с теми же данными)
Используется версия из ветки develop

**Comment by arkuznetsov** [comment]
@mors1eska
1. Закачку тестовых релизов пока не тестил.
2. Попробуй взять последний коммит с develop там были исправления по переадресации (работе с заголовками).

**Comment by mors1eska** [comment]
Добрый, спасибо за ответ, мой затуп (обновил девелоп, но не перекинул в место откуда вызывается)
На обычном релизе отработало
Если запрашивать тестовую, то ничего не происходит
![image](https://user-images.githubusercontent.com/34914654/97838531-6b6e0300-1cf1-11eb-87d9-d3a130118177.png)

С удовольствием помог бы в тестировании и разработке, но пока совсем не разобрался как отлаживать оскрипт

**Comment by arkuznetsov** [comment]
@mors1eska Для отладки нужно скачать отладчик: https://oscript.io/downloads/latest/x64/oscript-debug-0.6.0.vsix
В VSC на закладке плагинов выбрать сверху в "..." / "Установить из vsix".
Потом выбрать "Выполнить / открыть конфигурации" и сохранить получившийся lunch.json.
Далее ставим точки останова и запускаем отдаку по F5.

**Comment by mors1eska** [comment]
спасибо, на 1 шаг продвинулся
но пока не получается правильно команду запустить, что бы в отладке отработало
можете на примере одной команды подсказать?

я так понимаю, надо в json параметры прописать как-то
![image](https://user-images.githubusercontent.com/34914654/98165937-c3765680-1ef7-11eb-978f-b7e654e0be91.png)

**Comment by arkuznetsov** [comment]
@mors1eska Все верно в args пишутся параметры командной строки через ",":
```
"args": ["r", "-u", "1cuser", "-p", "1cpassword", "g", "--app-filter", "Бухгалтерия предприятия, редакция 3\\.0", "--version-start-date", "28.07.2020", "-p", "D:\\tmp\\distr", "-e", "--ep", "D:\\tmp\\tmplts"]
```

**Comment by mors1eska** [comment]
спасибо, вроде что-то получилось, отправил пул реквест на проверку

только понял, что не до конца продумал логику.
у меня задача такая:

Есть база, в которой есть сценарный тест
Я хочу что бы можно было легко (автоматически/полуавтоматически) обновить ее на последний актуальный или даже на тестовый релиз и запустить сценарный тест.

Можете подсказать, как это лучше организовать?

**Comment by arkuznetsov** [comment]
@mors1eska Я для целей автоматизации обновления держу в GIT рядом с доработанной конфигурацией отдельную ветку поставщика с типовой. В таком варианте я предложил бы следующий порядок:
1. Проверка наличия нового релиза 
2. Если появился, то загружаем и распаковываем
3. В репе переключаемся на ветку поставщика и выгружаем туда новый релиз (используя vanessa-runner)
4. Переключаемся на ветку для обновлений и актуализируем ее из master
5. Выполняем merge ветки поставщика в ветку для обновлений (тут скорее всего потребуется ручное решение конфликтов)
6. Собираем конфу из ветки для обновлений и накатываем на тестовую базу
7. Прогоняем тесты.
