### ISSUE TITLE
Ошибка при попытке загрузки релиза

### ISSUE THREAD

**Issue by CT144** [arkuznetsov/yard#41]
vesion 1.9.5
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\yard\src\Классы\ЗагрузчикРелизов1С.os / Ошибка в строке: 1043 / Свойство объекта не обнаружено (Идентификатор)}

**Comment by arkuznetsov** [comment]
Какую команду запускали, с какими параметрами.

**Comment by CT144** [comment]
yard releases -u "xxxxx" -p xxxxx get --app-filter "Бухгалтерия
предприятия КОРП, редакция 3.0" --version-filter %1 --path
"D:\TMP\_myTMP\1C\ОбработкаРелизов1С"  --extract --extract-path
"D:\CT\1C\distr1Cv8\ШаблоныОбновления\1c" --delete

параметр %1 = 3.0.140.40

С уважением,
 С.Тимонин


пт, 29 сент. 2023 г. в 12:53, Artem Kuznetsov ***@***.***>:

**Comment by arkuznetsov** [comment]
Я проверю, но у вас как минимум в фильтре приложения ошибка, там должен быть синтаксис регулярки, т.е. спец символы надо экранировать: "Бухгалтерия предприятия КОРП, редакция 3\.0" и параметр %1 = 3\.0\.140\.40.

**Comment by CT144** [comment]
Спасибо.
 Недели 2-3  назад все работало на версии 1,9,1. Ничего в батнике я не
менял. Фильтр приложения у меня это полное наименование приложения. И это
(технически) может быть значением для поиска по регулярке.

ЗЫ Пожелание.
Сделайте время ожидания ответа на запрос к сайту параметризуемым. Времени
ожидания "по умолчанию" на некоторых корпоративных компьютерах не хватает
для получения ответа.

С уважением,
 С.Тимонин


пт, 29 сент. 2023 г. в 15:54, Artem Kuznetsov ***@***.***>:

**Comment by CT144** [comment]
Качает, спасибо.

С уважением,
 С.Тимонин


пт, 29 сент. 2023 г. в 16:21, Artem Kuznetsov ***@***.***>:
