### ISSUE TITLE
[ЗагрузчикРелизов1С]: Не найдена ссылка на дистрибутив ...

### ISSUE THREAD

**Issue by CT144** [arkuznetsov/yard#42]
Yard v,1,9,6
Похоже 1С изменила "местоположение" дистрибутивов.

Попутно: как правильно задавать параметр --timeout?

**Comment by CT144** [comment]
ИНФОРМАЦИЯ - [ЗагрузчикРелизов1С]: Загрузка версии 1 из 1
ИНФОРМАЦИЯ - [ЗагрузчикРелизов1С]: Не найдена ссылка на дистрибутив "Бухгалтерия предприятия КОРП, редакция 3.0" версии 3.0.143.42.

и

ИНФОРМАЦИЯ - [ЗагрузчикРелизов1С]: Загрузка версии 1 из 1
ИНФОРМАЦИЯ - [ЗагрузчикРелизов1С]: Не найдена ссылка на дистрибутив "Бухгалтерия предприятия КОРП, редакция 2.0" версии 2.0.67.67.

**Comment by arkuznetsov** [comment]
1. Покажите настройки загрузки.
2. Вроде ничего не менялось на сайте релизов.
3. Всегда можно переопределить в настройках регулярки поиска ссылок на страницах.

**Comment by CT144** [comment]
Я в настройках ничего не менял. В один прекрасный день "все сломалось".
в батнике такая строка:
yard releases -u "12345" -p zzzzz get --app-filter "Бухгалтерия предприятия КОРП, редакция 3.0" --version-filter %1 --path "D:\TMP\_myTMP\1C\ОбработкаРелизов1С"  --extract --extract-path "D:\CT\1C\distr1Cv8\ШаблоныОбновления\1c" --delete 

Если "руками" загружать дистрибутив, то последовательность  читаемых страниц изменилась. Я и подумал, что путь до дистрибутива на сайте тоже изменился.

**Comment by arkuznetsov** [comment]
Попробуй с последней версией (1.9.7).

**Comment by CT144** [comment]
Скачал, спасибо.

**Comment by arkuznetsov** [comment]
Заработало?
