### ISSUE TITLE
Исключение при получении списка релизов "Бухгалтерии некоммерческой организации"

### ISSUE THREAD

**Issue by proDOOMman** [arkuznetsov/yard#51]
Конфиг файл примерно такой:
```
{
    "ИмяОбработки":"СписокРелизов1С",
    "Параметры":{
        "ИмяПользователя" : "",
        "ПарольПользователя" : "",
        "ФильтрПриложений" : ["Бухгалтерия некоммерческой организации"],
        "ПолучатьБетаВерсии": true,
        "ФильтрВерсийНачинаяСДаты" : "2024-03-01T00:00:00"
    }
}
```
При запуске yard происходит следующее:
```
ОТЛАДКА - Получена страница сайта "https://releases.1c.ru/version_files?nick=AccountingNPO&ver=3.0.149.2"
ОТЛАДКА - Авторизация: Получен ответ от ресурса "https://releases.1c.ru/version_file?nick=AccountingNPO&ver=3.0.149.2&path=AccountingNPO%5c3_0_149_2%5cAccountingNPO_3_0_149_2_setup1c.zip", Необходима авторизация
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\yard\src\Классы\ОбозревательСайта1С.os / Ошибка в строке: 596 / Авторизация: Ожидали что execution будет заполнен, но это не так!}
```
То есть yard пытается проверить ссылку на загрузку полного дистрибутива, но падает в исключение. Возможно потому что там требуется авторизация по СМС.

**Comment by arkuznetsov** [comment]
Гляну как посвободнее будет. Но лучше конечно PR! :-)
Собственно одна из первоочередных задач yard и есть автосборка полных CF-ников при наличии только обновлений (если есть хоть 1 CF предыдущей версии)!

**Comment by Daabramov** [comment]
> Возможно потому что там требуется авторизация по СМС.

А как это вообще обходить?

**Comment by proDOOMman** [comment]
> > Возможно потому что там требуется авторизация по СМС.
> 
> А как это вообще обходить?

Не падать в исключение, а просто считать что полный дистрибутив недоступен. Дистрибутив обновления при этом ведь скачивается без СМС
