### ISSUE TITLE
Добавить поддержку загрузки дистрибутивов EDT >= 2023.3.5

### ISSUE THREAD

**Issue by ovcharenko-di** [arkuznetsov/yard#54]
На данный момент EDT >= 2023.3.5 не загружается

**Comment by arkuznetsov** [comment]
Что пишет?

**Comment by ovcharenko-di** [comment]
Что-то там не найдено. Причина очевидна - текст ссылки и layout страницы
изменился.

Вт, 23 июля 2024 г. в 17:39, Artem Kuznetsov ***@***.***>:

**Comment by ovcharenko-di** [comment]
@arkuznetsov помогло, спасибо. закрываю issues

проблема на стороне onec-docker, пойду туда PR пульну
