### ISSUE TITLE
Пустая папка при загрузке релизов

### ISSUE THREAD

**Issue by igorkravitz** [arkuznetsov/yard#55]
Использую yard для загрузки релизов. Выполняю следующую команду:
![image](https://github.com/user-attachments/assets/b9409c88-07ce-460a-ba12-7c432fcb36c1)
команда успешно отрабатывает, но в папке C:\tmp\Analytics\1.78.1 ничего нет. Пробовал запускать в консоли от имени Администратора - тот же результат. Срабатываний Защитника Windows не было. Других антивирусов на ПК нет.
версия oscript 1.9.1.7 (х64)
версия yard 1.11.
версия ОС Windows 10 Pro 22H2
Раздел issues изучил, ничего похожего на свою ошибку не нашел, кроме "Защита от DDOS-атак при загрузке релизов". Но никакой информации при загрузке релиза нет.

И еще вопрос: какой фильтр по дистрибутиву писать, чтобы не грузить tar.bz2, а сразу zip?
![image](https://github.com/user-attachments/assets/3cdb59ae-fd44-4543-9d3c-78b42c06069f)
![image](https://github.com/user-attachments/assets/a3f82ebb-402c-4306-9a7a-d37287e9ad4d)
Пишу параметр --app-filter "1С:Аналитика*(zip)" программа пишет: "По адресу "/version_files?nick=Analytics&ver=1.78.1" не найдена ссылка для загрузки дистрибутива "1С:Аналитика" версии 1.78.1 по шаблону "Массив". Читал об этой ошибке в issue но комментарии не помогли. Если параметр --app-filter "1С:Аналитика" тогда программа находит дистрибутивы и по порядку начинает скачивать.

**Comment by arkuznetsov** [comment]
Скинь, плз, строку запуска или конфиг свой.

**Comment by igorkravitz** [comment]
yard releases --user "user" --pwd "password" get --app-filter "1С:Аналитика" --version-filter "1.78.1" --distr-filter "1С:Аналитика" --download-only --path "C:\tmp"

**Comment by arkuznetsov** [comment]
yard releases --user "user" --pwd "password" get --app-filter "1С:Аналитика" --version-filter "1.78.1" --distr-filter "1С:Аналитика.*(zip)" --download-only --path "C:\tmp"

Вот так работает.

**Comment by igorkravitz** [comment]
Попробовал указанный вариант. К сожалению, такой же результат. Папка пустая. На скрине видно, что программа отрабатывает все верно, возможно, даже скачивает. Но в конце что-то происходит и архива нет в папке. После выполнения в указанной папке сохраняется файл description.json.
![image](https://github.com/user-attachments/assets/808879dc-011c-4aca-9f58-d9f9ce62d2fb)
Пробовал как прямой вызов yard releases так и process с файлом настройки. Пробовал отключать брандмауэр, защитник windows - тот же результат, файл не сохраняется.
На ПК программа 7-Zip установлена, програмно из командной строки архивы RAR распаковывает.
Могу только сказать, что получилось скачать с помощью метода скачивания файлов с помощью cURL, используя Cookies браузера (Защитник windows, брандмауэр был включен): 
- авторизоваться на портале 1C через браузер
- зайти на страницу релиза 
- открыть инструменты разработчика Ctrl + Shift + I
- открыть раздел Network 
- вручную из браузера сохранить релиз
- в разделе Network правой кнопкой мыши вызвать команду Copy - Copy as cURL (cmd)
- вставить скопированный фрагмент в файл cmd и дописать --output <имя диска>:\<путь к папке>\<имя файла[.zip]>

По данной команде файл релиза скачивается, но этот способ неудобный, нет прямой связи между именем конфигурации и ссылкой для скачивания, и Cookies со временем будут неактуальны, нужно будет авторизоваться снова

**Comment by igorkravitz** [comment]
Файл настроек для process - releases-settings.json
```
{
  "ИмяОбработки":"СписокРелизов1С",
  "Параметры":{
      "ИмяПользователя" : "user",
      "ПарольПользователя" : "password",
      "ФильтрПриложений" : ["1С:Аналитика"], 
      "ФильтрВерсий" : ["1.78.1"],
      "ФильтрВерсийНачинаяСДаты" : "2022-01-01T00:00:00"
  },
  "Обработчики":[
      {
          "ИмяОбработки":"ЗагрузчикРелизов1С",
          "ИдОбработчика":"1С:Аналитика",
          "Параметры":{
              "ИмяПользователя" : "user",
              "ПарольПользователя" : "password",
              "ИмяПриложения": "1С:Аналитика",
              "ФильтрДистрибутива" : "1С:Аналитика. Версия 1.78.1. Дистрибутив \\(zip\\)",
              "КаталогДляСохранения" : "$workDir\\tmp\\distr",
              "РаспаковыватьEFD" : false,
              "ФайлыДляРаспаковкиEFD" : [],
              "УдалитьПослеРаспаковкиEFD" : false,
              "ОписаниеПоследнейВерсии" : "$workDir\\description.json",
              "НачатьСПоследнейВерсии" : true,
              "ОграничениеКоличества" : 2,
              "ЗагружатьСуществующие" : false,
              "ТолькоСкачать": true
          }
      }
  ]
}
```

**Comment by arkuznetsov** [comment]
Видимо причина где-то у вас, т.к. у меня загружается как при указании параметров в командной строке (см. мой комментарий выше) так и с указанными настройками в файле json.
Можно включить отладочный лог (`set LOGOS_CONFIG=logger.rootLogger=DEBUG`) и попробовать понять причину по его содержимому.
