### ISSUE TITLE
Добавить поддержку скачивания платформы

### ISSUE THREAD

**Issue by yuriybylinkin** [arkuznetsov/yard#6]
На странице скачивания платформы много вариантов - клиент, сервер, для Windows, для Linux, 64-бит и тд. Хорошо было бы отбирать и по такому варианту нужный для скачивания вариант

**Comment by yuriybylinkin** [comment]
я слоупок, нашел параметр --distr-filter
Но не очень понятно, как скачать нужную версию - мне надо скачать deb-версию 64 сервера.
Указание "Cервер 1С:Предприятия (64-bit) для DEB", "сервер.*deb64" не приводит ни к чему.
А "64.*DEB" приводит к скачиванию клиента.

**Comment by arkuznetsov** [comment]
Спасибо, посмотрю!

**Comment by arkuznetsov** [comment]
Фильтр - это регулярка, нужно все служебные символы экранировать и скобки в том числе. Например, рабочий вариант:
```
--distr-filter "Cервер 1С:Предприятия \(64-bit\) для DEB-based"
```
