### ISSUE TITLE
Конвертирование конфигурации БП 3.0.161.19 с автоматическим скачиванием завершается ошибкой

### ISSUE THREAD

**Issue by senja006** [arkuznetsov/yard#61]
При запуске конвертирования в проект EDT типовой конфигурации Бухгалтерия предприятия релиза 3.0.161.19 с ее автоматическим скачиванием с сайта 1С появляется ошибка (скрин 1).

Наверное, скачивается версия для обновления, не для начальной установки - в каталоге шаблона нет файла `cf`, только `cfu` (скрин 2).

### Скрин 1

![image](https://github.com/user-attachments/assets/0dc7dbfe-f045-4a65-91d9-701378defe70)

### Скрин 2

![image](https://github.com/user-attachments/assets/5357ae79-c197-4c3e-afd8-dcad22a5ecef)

**Comment by arkuznetsov** [comment]
Ну да, так должно быть.
А какое поведение ожидается?
Какая настройка запуска yard используется?

**Comment by arkuznetsov** [comment]
Для БП полный дистриб, доступен только по SMS.
Собственно весь yard отчасти затевался для того, чтобы автоматом собирать СА из CFU. :-)
